apiVersion: apps/v1
kind: Deployment
metadata:
  name: animal-adoption
  labels:
    app: animal-adoption
spec:
  replicas: 2
  selector:
    matchLabels:
      app: animal-adoption
  template:
    metadata:
      labels:
        app: animal-adoption
    spec:
      containers:
      - name: animal-adoption
        image: akshit0o/animal-adoption:latest     # Placeholder until first deploy
        ports:
        - containerPort: 80
