apiVersion: v1
kind: Service
metadata:
  name: happy-paws-green
  namespace: happy-paws-bg
  labels:
    app: happy-paws
spec:
  selector:
    app: happy-paws
    track: green
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
